package contract

const (
	EXEC_CONTRACT_FUNC_NAME_PUT_SATELLITE = "PutSatellite"

	EXEC_CONTRACT_FUNC_NAME_GEN_INSTRUCTION = "GenInstruction"
	EXEC_CONTRACT_FUNC_NAME_PUT_INSTRUCTION = "PutInstruction"

	EXEC_CONTRACT_FUNC_NAME_GET_DEBRIS = "GetDebris"

	EXEC_CONTRACT_FUNC_NAME_PUT_CONTROL = "PutControl"

	EXEC_CONTRACT_FUNC_NAME_PUT_FAULT = "PutFault"

	EXEC_CONTRACT_FUNC_NAME_PUT_COMMSTATE = "PutCommState"

	EXEC_CONTRACT_FUNC_NAME_PUT_NETSTATE = "PutNetState"

	EXEC_CONTRACT_FUNC_NAME_PUT_OPERATION = "PutNetOperation"
)
