package contract

const (
	EXEC_CONTRACT_FUNC_NAME_PUT_SATELLITE = "put_satellite"

	EXEC_CONTRACT_FUNC_NAME_GEN_INSTRUCTION = "gen_instruction"
	EXEC_CONTRACT_FUNC_NAME_PUT_INSTRUCTION = "put_instruction"

	EXEC_CONTRACT_FUNC_NAME_PUT_CONTROL = "put_control"

	EXEC_CONTRACT_FUNC_NAME_PUT_FAULT = "put_fault"

	EXEC_CONTRACT_FUNC_NAME_PUT_COMMSTATE = "put_commstate"

	EXEC_CONTRACT_FUNC_NAME_PUT_NETSTATE = "put_netstate"

	EXEC_CONTRACT_FUNC_NAME_PUT_OPERATION = "put_operation"
)
