package contract

const (
	MASTER_CONTRACT_FUNC_NAME_PUT_DEBRIS = "PutDebris"

	MASTER_CONTRACT_FUNC_NAME_PUT_INSTRUCTION = "PutInstruction"

	MASTER_CONTRACT_FUNC_NAME_PUT_ORBIT = "PutOrbit"

	MASTER_CONTRACT_FUNC_NAME_PUT_CONSTELLATION = "PutConstellation"

	MASTER_CONTRACT_FUNC_NAME_PUT_LOGINLOG = "PutLoginLog"

	MASTER_CONTRACT_FUNC_NAME_PUT_OPERATION = "PutOperation"

	MASTER_CONTRACT_FUNC_NAME_PUT_COMMSTATE = "PutCommState"

	MASTER_CONTRACT_FUNC_NAME_PUT_CONTROL = "PutControl"

	MASTER_CONTRACT_FUNC_NAME_PUT_FAULT = "PutFault"

	MASTER_CONTRACT_FUNC_NAME_PUT_NETSTATE = "PutNetState"

	MASTER_CONTRACT_FUNC_NAME_PUT_SATELLITE = "PutSatellite"
)
