package contract

const (
	MASTER_CONTRACT_FUNC_NAME_PUT_DEBRIS = "put_debris"

	MASTER_CONTRACT_FUNC_NAME_PUT_INSTRUCTION = "put_instruction"

	MASTER_CONTRACT_FUNC_NAME_PUT_ORBIT = "put_orbit"

	MASTER_CONTRACT_FUNC_NAME_PUT_CONSTELLATION = "put_constellation"

	MASTER_CONTRACT_FUNC_NAME_PUT_LOGINLOG = "put_loginlog"

	MASTER_CONTRACT_FUNC_NAME_PUT_OPERATION = "put_operation"

	MASTER_CONTRACT_FUNC_NAME_PUT_COMMSTATE = "put_commstate"

	MASTER_CONTRACT_FUNC_NAME_PUT_CONTROL = "put_control"

	MASTER_CONTRACT_FUNC_NAME_PUT_FAULT = "put_fault"

	MASTER_CONTRACT_FUNC_NAME_PUT_NETSTATE = "put_netstate"

	MASTER_CONTRACT_FUNC_NAME_PUT_SATELLITE = "put_satellite"
)
