package contract

const (
	CONTRACT_FUNC_NAME_PUT_DEBRIS        = "PutDebris"
	CONTRACT_FUNC_NAME_GET_DEBRIS        = "GetDebris"
	CONTRACT_FUNC_NAME_PUT_INSTRUCTION   = "PutInstruction"
	CONTRACT_FUNC_NAME_GET_INSTRUCTION   = "GetInstruction"
	CONTRACT_FUNC_NAME_PUT_ORBIT         = "PutOrbit"
	CONTRACT_FUNC_NAME_GET_ORBIT         = "GetOrbit"
	CONTRACT_FUNC_NAME_PUT_CONSTELLATION = "PutConstellation"
	CONTRACT_FUNC_NAME_GET_CONSTELLATION = "GetConstellation"
	CONTRACT_FUNC_NAME_PUT_LOGINLOG      = "PutLoginLog"
	CONTRACT_FUNC_NAME_GET_LOGINLOG      = "GetLoginLog"
	CONTRACT_FUNC_NAME_PUT_OPERATION     = "PutOperation"
	CONTRACT_FUNC_NAME_GET_OPERATION     = "GetOperation"
)
