server_port: 8086

log_config:
  log_level: INFO
  log_path: ../log/default.log                             
  max_size: 10       # (MB)                               
  max_age: 30        # (day)                            
  max_backups: 1000    
  show_line: true
  show_color: true
  is_brief: false
  json_format: false    
  log_in_console: false                    

db_config:
  user: root
  password: 123456
  ip: 172.16.2.225
  port: 13306
  dbname: chainmaker


block_chain_config:
  - user_name: master
    user_pwd: 1234
    sdk_config_path: ../conf/masterchain_sdk_config.yaml

  - user_name: exec
    user_pwd: 1234
    sdk_config_path: ../conf/satellitechain_sdk_config.yaml

master_contract: 
  name: masterC
  chain_id: chain_dcwjj

exec_contract: 
  name: execC
  chain_id: chain_dcwjc
