server_port: 8086

log_config:
  log_level: INFO
  log_path: ./log/default.log                             
  max_size: 10       # (MB)                               
  max_age: 30        # (day)                            
  max_backups: 1000    
  show_line: true
  show_color: true
  is_brief: false
  json_format: false    
  log_in_console: false                    

db_config:
  user: root
  password: 123456
  ip: 127.0.0.1
  port: 3306
  dbname: chainmaker


block_chain_config:
  - user_name: master
    user_pwd: 1234
    sdk_config_path: ../conf/masterchain_sdk_config.yaml

  - user_name: exec
    user_pwd: 1234
    sdk_config_path: ../conf/satellitechain_sdk_config.yaml

master_contract:
  debris:
    name: "debris"
    version: "v1.0.0"
  instruction:
    name: "instruction"
    version: "v1.0.0"
  orbit:
    name: "orbit"
    version: "v1.0.0"
  constellation:
    name: "constellation"
    version: "v1.0.0"
  loginlog:
    name: "loginlog"
    version: "v1.0.0"
  operation:
    name: "operation"
    version: "v1.0.0"
exec_contract:
  debris:
    name: "debris"
    version: "v1.0.0"
  satellite:
    name: "satellite"
    version: "v1.0.0"
  instruction:
    name: "instruction"
    version: "v1.0.0"
  exec:
    name: "exec"
    version: "v1.0.0"
  control:
    name: "control"
    version: "v1.0.0"
  fault:
    name: "fault"
    version: "v1.0.0"
  commstate:
    name: "commstate"
    version: "v1.0.0"
  netstate:
    name: "netstate"
    version: "v1.0.0"
  operation:
    name: "operation"
    version: "v1.0.0"